"""Add candle market data fields

Revision ID: 76b8ec673cae
Revises: 81cd83269c19
Create Date: 2026-08-26 13:51:19.421194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b8ec673cae'
down_revision: Union[str, Sequence[str], None] = '81cd83269c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('vwap', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('candles', sa.Column('trade_count', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_candle_symbol_timeframe_timestamp', 'candles', ['symbol', 'timeframe', 'timestamp'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candle_symbol_timeframe_timestamp', 'candles', type_='unique')
    op.drop_column('candles', 'trade_count')
    op.drop_column('candles', 'vwap')
    # ### end Alembic commands ###
